using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
//using Holoo1Space.Frm;
//using Holoo1Space.Class;
using DevExpress.Utils;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Views.Grid;
using static DevExpress.Utils.Diagnostics.GUIResources;
using System.Data.Entity;
using CncApp_Final.Frm;

//using Holoo1Space.Frm.Host;

namespace CncApp_Final
{
    public partial class MainForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public MainForm()
        {
            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Orders.Load();
            // This line of code is generated by Data Source Configuration Wizard
            ordersBindingSource.DataSource = dbContext.Orders.Local.ToBindingList();




        }


        private void XfrmVCF_Load(object sender, EventArgs e)
        {
            RefreshVCFX();
        }

        private void RefreshVCFX()
        {
            SavePosition();

            //// TODO: This line of code loads data into the 'alpaDataSet.VCFX_Summary' table. You can move, or remove it, as needed.
            //this.vCFX_SummaryTableAdapter.Fill(this.alpaDataSet.VCFX_Summary);

            RestorePosition();
        }

        private void bbiEdit_ItemClick(object sender, ItemClickEventArgs e)
        {
            ribbonControl.BeginInit();
            int order_Id = (int)gridView.GetFocusedRowCellValue(colId);
            FrmOrder frmFactureX = new FrmOrder(order_Id);
            frmFactureX.ShowDialog();
            if (frmFactureX.DialogResult == DialogResult.OK)
            {
                RefreshVCFX();
            }
            ribbonControl.EndInit();
        }

        private void bbiNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            FrmOrder frmOrder = new FrmOrder();
            frmOrder.ShowDialog();
            if (frmOrder.DialogResult == DialogResult.OK)
            {
                RefreshVCFX();
                RestorePosition(frmOrder._VCF_Id);
            }
        }

        private void bbiFrame_ItemClick(object sender, ItemClickEventArgs e)
        {
            //new XfrmFrame().ShowDialog();
        }

        private void gridView_DoubleClick(object sender, EventArgs e)
        {
            //DXMouseEventArgs ea = e as DXMouseEventArgs;
            //GridView view = sender as GridView;
            //GridHitInfo info = view.CalcHitInfo(ea.Location);
            //if (info.InRow || info.InRowCell)
            //{
            //    bbiEdit.PerformClick();
            //    //string colCaption = info.Column == null ? "N/A" : info.Column.GetCaption();
            //    //MessageBox.Show(string.Format("DoubleClick on row: {0}, column: {1}.", info.RowHandle, colCaption));
            //}

        }

        public void SavePosition()
        {
            //this.gridView = (GridView)this.gridControl.MainView;
            //focusedRowHandel = gridView.FocusedRowHandle;
            //topRowIndex = gridView.TopRowIndex;
        }

        public void RestorePosition()
        {
            //gridView.FocusedRowHandle = focusedRowHandel;
            //gridView.TopRowIndex = topRowIndex;
        }

        public void RestorePosition(int _NewVCF_Id)
        {
            //gridView.FocusedRowHandle = gridView.LocateByValue("VCF_Id", _NewVCF_Id);
        }

        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
            //string vCF_Ids = "";
            //for (int handle = 0; handle < gridView.RowCount; handle++)
            //{
            //    vCF_Ids += gridView.GetRowCellValue(handle, colVCF_Id).ToString() + ",";
            //}
            //vCF_Ids = vCF_Ids.TrimEnd(',');
            //ReportHelper.PrintVCFX_List(vCF_Ids);
        }

        private void bbiPrintSelected_ItemClick(object sender, ItemClickEventArgs e)
        {
            //ReportHelper.PrintCurrent((int)gridView.GetFocusedRowCellValue(colVCF_Id));
        }

        private void bbiPrintAll_ItemClick(object sender, ItemClickEventArgs e)
        {
            //List<int> vCF_Ids = new List<int>();
            //for (int handle = 0; handle < gridView.RowCount; handle++)
            //{
            //    vCF_Ids.Add((int)gridView.GetRowCellValue(handle, colVCF_Id));
            //}
            //ReportHelper.PrintAll(vCF_Ids);
        }

        private void bbiSyncSpace_ItemClick(object sender, ItemClickEventArgs e)
        {
            //new XfrmUpdateArticle().ShowDialog();
        }

        private void bbiSyncCustomer_ItemClick(object sender, ItemClickEventArgs e)
        {
            //new XfrmUpdateCustomer().ShowDialog();
        }

        private void bbiExportFaktorToMahak_ItemClick(object sender, ItemClickEventArgs e)
        {
            //new XfrmExportToMahak().ShowDialog();
        }

        private void bbiRefresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            RefreshVCFX();
        }

        private void bbiHostForm_ItemClick(object sender, ItemClickEventArgs e)
        {
            //XfrmHostMain xfrmHostMain = new XfrmHostMain();
            //xfrmHostMain.ShowDialog();
        }

        private void bbiBackupDatabase_ItemClick(object sender, ItemClickEventArgs e)
        {
            //FrmBackupRestoryDatabase frmRestoryDatabase = new FrmBackupRestoryDatabase();
            //frmRestoryDatabase.ShowDialog();
            //bbiRefresh.PerformClick();
        }

        private void ribbonControl_Click(object sender, EventArgs e)
        {

        }
    }
}