using CncApp_Final.Data;
using CncApp_Final.Entities;
using CncApp_Final.Frms.Base;
using CncApp_Final.Frms.EditForms;
using CncApp_Final.Services;
using DevExpress.XtraBars;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CncApp_Final.Frms.ListForms
{
    public partial class FrmCustomerList :
#if !DEBUG
                    BaseFormList
#else
                    BaseFormListDesignerSafe
#endif
    {
        public FrmCustomerList() : base(new EfListService<Customer>(new AppDbContext()))
        {
            InitializeComponent();
            this.Load += BaseFormList_Load;
            this.StartPosition = FormStartPosition.CenterParent;
            // This line of code is generated by Data Source Configuration Wizard
            // Uncomment next line to set the total number of data records stored within your source
            // unboundSource1.SetRowCount(42);
            // This line of code is generated by Data Source Configuration Wizard
            this.unboundSource1.ValueNeeded += unboundSource1_ValueNeeded;
            // This line of code is generated by Data Source Configuration Wizard
            this.unboundSource1.ValuePushed += unboundSource1_ValuePushed;
        }

        protected override RibbonControl GetRibbonControl() => ribbonControl;
        protected override GridControl GetGridControl() => gridControl;
        protected override GridView GetGridView() => gridView;
        protected override BarButtonItem GetNewButton() => bbiNew;
        protected override BarButtonItem GetEditButton() => bbiEdit;
        protected override BarButtonItem GetDeleteButton() => bbiDelete;
        protected override BarButtonItem GetRefreshButton() => bbiRefresh;
        protected override BarButtonItem GetPrintPreviewButton() => bbiPrintPreview;
        protected override BarStaticItem GetRecordsCountItem() => bsiRecordsCount;

        protected override string GetFormTitle() => "لیست ورق ها";

        protected override IEditForm CreateEditForm(int id, bool isReadOnly)
        {
            var service = new EfCrudService<Customer>(new AppDbContext());
            return new FrmCustomerEdit(id, isReadOnly, service);
        }


        protected override void BaseFormList_Load(object sender, EventArgs e)
        {

        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValueNeeded(object sender, DevExpress.Data.UnboundSourceValueNeededEventArgs e)
        {
            // Handle this event to obtain data from your data source
            // e.Value = something /* TODO: Assign the real data here.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValuePushed(object sender, DevExpress.Data.UnboundSourceValuePushedEventArgs e)
        {
            // Handle this event to save modified data back to your data source
            // something = e.Value; /* TODO: Propagate the value into the storage.*/
        }
    }
}