using DevExpress.XtraEditors;
using DevExpress.XtraLayout;
using DevExpress.XtraLayout.Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CncApp_Final.Frm
{
    public partial class FrmCustomers : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public FrmCustomers()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Customers.Load();
            // This line of code is generated by Data Source Configuration Wizard
            customersBindingSource.DataSource = dbContext.Customers.Local.ToBindingList();
        }
       
        private void FrmCustomerEdit_Load(object sender, EventArgs e)
        {
            
        }

        private void bbiEditCustomer_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            int customer_Id = (int)gridView.GetFocusedRowCellValue(colId);
            Frm.FrmCustomerEdit frmCustomerEdit = new Frm.FrmCustomerEdit(customer_Id,false);
            frmCustomerEdit.ShowDialog();
        }

        private void bbiNewCustomer_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Frm.FrmCustomerEdit frmCustomerEdit = new Frm.FrmCustomerEdit(0, false);
            frmCustomerEdit.ShowDialog();
        }
    }
}
