using DevExpress.LookAndFeel;
using DevExpress.XtraBars;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml.Linq;

using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
//using System.Windows.Documents;
using System.Windows.Forms;
//using CEWorld.Convert;
using DevExpress.XtraEditors;
//using DevExpress.XtraTreeList;
//using DrawFocusRectStyle = DevExpress.XtraTreeList.DrawFocusRectStyle;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
//using CustomXtraGridBorder;
using DevExpress.Utils;
using DevExpress.XtraBars.Docking2010.Views.Widget;
using System.Data.Entity;
using System.Runtime.Remoting.Contexts;

namespace CncApp_Final.Frm
{
    public partial class FrmOrder : DevExpress.XtraBars.Ribbon.RibbonForm
    {
       
        public int _VCF_Id = -1;
        private int _VCF_Id_Org = -1;
        private bool _IsNewFaktor = false;


        public FrmOrder()
        {
            InitializeComponent();
            _IsNewFaktor = true;

            
        }

        public FrmOrder(int vCF_Id)
        {
            InitializeComponent();
            _VCF_Id = vCF_Id;
            _VCF_Id_Org = vCF_Id;
        }



        //************************************************************************************************************************************



        private void FrmFacture_Load(object sender, EventArgs e)
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();

            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Orders.Load();
            dbContext.OrderDetails.Load();
            dbContext.Customers.Load();

            // This line of code is generated by Data Source Configuration Wizard
            orderDetailsBindingSource.DataSource = dbContext.OrderDetails.Local.ToBindingList();
            orderBindingSource.DataSource = dbContext.Orders.Local.ToBindingList();
            customersBindingSource.DataSource = dbContext.Customers.Local.ToBindingList();


            InitControl();
            InitDataToControl();



        }



        //************************************************************************************************************************************



        #region Load Data To Form Control


        private void InitDataToControl()
        {
            if (_IsNewFaktor)
            {
                int orderId = _VCF_Id; // یا از فرم بگیرید
                CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();

                var orderWithDetails = dbContext.Orders
                    .Include(o => o.OrderDetails)
                    .Include(o => o.Customer)
                    .FirstOrDefault(o => o.Id == orderId);

                if (orderWithDetails == null)
                {
                    MessageBox.Show("سفارش یافت نشد.");
                    orderBindingSource.DataSource = null;
                    orderDetailsBindingSource.DataSource = null;
                    return;
                }

                // فقط سفارش انتخاب شده
                orderBindingSource.DataSource = orderWithDetails;

                // فقط جزئیات همین سفارش (بهترین روش برای BindingSource)
                orderDetailsBindingSource.DataSource = orderWithDetails.OrderDetails;

                //_VCF_Id = (int)vCFXTableAdapter.GetNewVCF_Id();
                //InitNewRowVCF_X(_VCF_Id);
                ribbonControl1.ApplicationCaption = "ثبت فاکتور جدید";
            }
            else
            {
                //vCFXTableAdapter.FillBy(this.alpaDataSet.VCFX, _VCF_Id);
                //ribbonControl1.ApplicationCaption = "ویرایش فاکتور";

            }



            ////serviceTableAdapter.Fill(this.alpaDataSet.Service, _VCF_Id);

            ////ucFrameSelector1.ServiceTable = alpaDataSet.Service;
            //ucFrameSelector1.VCF_Id(_VCF_Id);
            //ucAddress1.VCF_Id(_VCF_Id);
            //ucCost1.VCF_Id(_VCF_Id);
            //ucVCF_Space1.VCF_Id(_VCF_Id);

            //Service_RowsChanged(this, EventArgs.Empty);

            //if (_IsNewFaktor)
            //{
            //    lueCustomer.EditValue = "2";
            //    lueCustomer.Focus();
            //}

            //lsbNavigationFrame.SelectedIndex = 0;

        }

        private void InitNewRowVCF_X(int _VCF_Id)
        {
            //AlpaDataSet.VCFXRow newRow = this.alpaDataSet.VCFX.NewVCFXRow();
            //newRow.VCF_Time = DateTime.Now.ToString("HH:mm");
            //newRow.VCF_Id = _VCF_Id;

            ////txbVCF_Id.EditValue = newRow.VCF_Id;
            ////txbVCF_Id.EditValue = 77;

            //newRow.VCF_NaghdB = 0;
            //newRow.VCF_KartKhanB = 0;
            //newRow.VCF_KartKhan = 0;
            //newRow.VCF_Vasetehtype = false;
            //newRow.VCF_VasetehPrice = 0;
            //newRow.VCF_CountFirst = 0;
            //newRow.VCF_Cust_Rent = 0;
            //newRow.VC_Hazineh = 0;
            //newRow.VCT_Price = 0;
            //newRow.VCT_Day = 0;
            //newRow.VCTName = "";
            //newRow.VCT_LateDayPrice = 0;




            //this.alpaDataSet.VCFX.AddVCFXRow(newRow);
        }

        #endregion


        //************************************************************************************************************************************





        #region ***************  Init control focused color    ***************

        private void InitControl()
        {
            //txbTime.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            //txbDate.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            //txbRDate.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            //txbDays.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            ////txbPriceIndex.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;

            //txbComment.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            ////gridView1.Appearance.FocusedCell.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
        }

        private int _color;
        private void gridControl1_Enter(object sender, EventArgs e)
        {
            //_color = gridView1.Appearance.FocusedCell.BackColor.ToArgb();
            //gridView1.Appearance.FocusedCell.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;

            //var culture = System.Globalization.CultureInfo.GetCultureInfo("fa-IR");
            //var language = InputLanguage.FromCulture(culture);
            //if (InputLanguage.InstalledInputLanguages.IndexOf(language) >= 0)
            //    InputLanguage.CurrentInputLanguage = language;
        }

        private void gridControl1_Leave(object sender, EventArgs e)
        {
            //gridView1.PostEditor();

            //gridView1.Appearance.FocusedCell.BackColor = Color.FromArgb(_color);
        }


        InputLanguage original;
        private void textBox_Enter(object sender, EventArgs e)
        {
            original = InputLanguage.CurrentInputLanguage;
            var culture = System.Globalization.CultureInfo.GetCultureInfo("fa-IR");
            var language = InputLanguage.FromCulture(culture);
            if (InputLanguage.InstalledInputLanguages.IndexOf(language) >= 0)
                InputLanguage.CurrentInputLanguage = language;
            else
                InputLanguage.CurrentInputLanguage = InputLanguage.DefaultInputLanguage;
        }

        private void textBox_Leave(object sender, EventArgs e)
        {
            InputLanguage.CurrentInputLanguage = original;
        }

        #endregion


        //************************************************************************************************************************************




        //************************************************************************************************************************************




        //************************************************************************************************************************************


        #region Temp And Unused Method



        /// <summary>
                /// کرفتن متن ستون از گریدیو
                /// </summary>
                /// <param name="gw"></param>
                /// <param name="column"></param>
                /// <returns></returns>
        private static string GetTextColumnValue(GridView gw, string column)
        {
            if (gw.RowCount <= 0)
            {
                return " ";
            }
            try
            {
                int i = gw.FocusedRowHandle;
                return gw.IsGroupRow(i)
                ? gw.GetGroupRowValue(i, gw.Columns[column]).ToString()
                : gw.GetRowCellValue(i, column).ToString();
            }
            catch
            {
                MessageBox.Show($@"درخواستی در کنترل انتخابی موجود نمی باشد( {column} ) ستون");
                return " ";
            }
        }

        #endregion


        //************************************************************************************************************************************


        #region Faktor Dates TextBox Handler


        private void txbDate_Enter(object sender, EventArgs e)
        {
            //txbDate.DeselectAll();
            //txbDate.SelectionStart = 0;
            //txbDate.SelectionLength = 2;
            ////txbDescription.Text = string.Format("SelectionStart = {0}    SelectionLength={1}", txbDate.SelectionStart, txbDate.SelectionLength);
        }

        private void txbRDate_Enter(object sender, EventArgs e)
        {
            //txbRDate.DeselectAll();
            //txbRDate.SelectionStart = 0;
            //txbRDate.SelectionLength = 2;
        }

        private void txbDate_EditValueChanged(object sender, EventArgs e)
        {
            //var pc = new PersianCalendar();

            //PersianCalendar persianCal = new System.Globalization.PersianCalendar();
            ////DateTime GregorianDate11 = DateTime.Parse("1983/08/03");
            //DateTime PersianDate = DateTime.Parse(txbDate.EditValue.ToString());
            //DateTime GregorianDate = persianCal.ToDateTime(PersianDate.Year, PersianDate.Month, PersianDate.Day, 12, 0, 0, 0);
            //var dtR1 = PersianDate.AddDays(Convert.ToDouble(txbDays.EditValue));
            //txbRDate.EditValue = dtR1.ToString("d");
        }

        private void txbRDate_EditValueChanged(object sender, EventArgs e)
        {
            //var pc = new PersianCalendar();

            //PersianCalendar persianCal = new System.Globalization.PersianCalendar();
            ////DateTime GregorianDate11 = DateTime.Parse("1983/08/03");
            //DateTime PersianDate = DateTime.Parse(txbDate.EditValue.ToString());
            //DateTime PersianDateR = DateTime.Parse(txbRDate.EditValue.ToString());

            //TimeSpan x = PersianDateR - PersianDate;
            //txbDays.EditValue = x.Days.ToString("");
        }

        private void txbDays_EditValueChanged(object sender, EventArgs e)
        {
            //var pc = new PersianCalendar();

            //PersianCalendar persianCal = new System.Globalization.PersianCalendar();
            ////DateTime GregorianDate11 = DateTime.Parse("1983/08/03");
            //DateTime PersianDate = DateTime.Parse(txbDate.EditValue.ToString());
            //DateTime GregorianDate = persianCal.ToDateTime(PersianDate.Year, PersianDate.Month, PersianDate.Day, 12, 0, 0, 0);
            //var dtR1 = PersianDate.AddDays(Convert.ToDouble(txbDays.EditValue));
            //txbRDate.EditValue = dtR1.ToString("d");

        }



        #endregion


        //************************************************************************************************************************************




        //************************************************************************************************************************************




        //************************************************************************************************************************************



        private void UpdateRelaytedTable(int _NewVCF_Id)
        {
            //var x1 = ucFrameSelector1.alpaDataSet.VCF_Frame;
            //var x2 = ucCost1.alpaDataSet.VCF_Cost;
            //var x3 = ucVCF_Space1.alpaDataSet.VCF_Space;

            //var zz = alpaDataSet.VCFX.Rows[0].RowState;

            //this.Validate();
            //vCFX1BindingSource.EndEdit();

            //ucFrameSelector1.UpdateDatabase(_NewVCF_Id);
            //ucCost1.UpdateDatabase(_NewVCF_Id);
            //ucVCF_Space1.UpdateDatabase(_NewVCF_Id);
            //vCFXTableAdapter.Update(alpaDataSet.VCFX);
        }



        private void txbDescription_KeyPress(object sender, KeyPressEventArgs e)
        {
            //if (e.KeyChar == 'ی')
            //    e.KeyChar = 'ي';
        }


        private void btnNewCustomer_Click(object sender, EventArgs e)
        {
            //FrmNewCustomer frmNewCustomer = new FrmNewCustomer();
            //frmNewCustomer.ShowDialog();

            //if (frmNewCustomer.C_Code != null)
            //{
            //    this.cUSTOMERTableAdapter.Fill(this.alpaDataSet.CUSTOMER);
            //    lueCustomer.EditValue = frmNewCustomer.C_Code;
            //}
        }




        //************************************************************************************************************************************




        private void ucFrameSelector1_AddressFrameAdd(object sender, EventArgs e)
        {
            ////int focusedRowHandle = grdvAddressFrame.FocusedRowHandle;

            ////if (grdvAddressFrame.FocusedRowHandle >= 0)
            ////{
            ////    grdvAddressFrame.FocusedRowHandle = grdvAddressFrame.GetParentRowHandle(grdvAddressFrame.FocusedRowHandle);
            ////}

            ////VCF_Frame addressFrame = new VCF_Frame();
            ////addressFrame.Address = grdvAddressFrame.GetFocusedValue().ToString();
            ////addressFrame.FrameId = ucFrameSelector1.FrameId;
            ////addressFrame.FrameName = ucFrameSelector1.cmbFrameName.Text;
            ////addressFrame.FrameSize = ucFrameSelector1.cmbFrameSize.Text;
            ////addressFrame.FrameSize = ucFrameSelector1.lookUpEdit1.Text;
            ////addressFrame.Count = Convert.ToInt32(ucFrameSelector1.cmbFrameCount.Text.Replace(" عدد", ""));
            ////_AddressFrameCollection.Add(addressFrame);

            ////grdvAddressFrame.RefreshData();
            ////grdvAddressFrame2.RefreshData();
            ////grdvAddressFrame2.ExpandAllGroups();
            ////grdvAddressFrame.ExpandAllGroups();

            ////grdvAddressFrame.FocusedRowHandle = focusedRowHandle;
        }












        private void txbCustomerX_Enter(object sender, EventArgs e)
        {
            //txbCustomerX.SelectAll();
        }

        private void grdvServices_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            //if (e.Column.Name == colDiscountedPrice.Name)
            //{
            //    string TableName = grdvServices.GetRowCellValue(e.RowHandle, colTable).ToString();
            //    int Id = (int)grdvServices.GetRowCellValue(e.RowHandle, colId);
            //    int value = (int)grdvServices.GetRowCellValue(e.RowHandle, colDiscountedPrice);

            //    switch (TableName)
            //    {
            //        case "Frame":
            //            ucFrameSelector1.SetRowDiscountedPrice(Id, value);
            //            break;

            //        case "Cost":
            //            ucCost1.SetRowDiscountedPrice(Id, value);
            //            break;
            //    }
            //}

            //grdvServices.UpdateSummary();
            //txbSumNetPrice.EditValue = Convert.ToInt32(colNetPrice.SummaryItem.SummaryValue);

        }

        private void Service_RowsChanged(object sender, EventArgs e)
        {
            //AlpaDataSet.ServiceDataTable ServiceTable = alpaDataSet.Service;
            //ServiceTable.Clear();

            //int focusedHande = grdvServices.FocusedRowHandle;


            //foreach (AlpaDataSet.VCF_FrameRow item in ucFrameSelector1.alpaDataSet.VCF_Frame)
            //{
            //    if (item.RowState == DataRowState.Deleted)
            //        continue;

            //    AlpaDataSet.ServiceRow newrow = ServiceTable.NewServiceRow();
            //    newrow.Id = item.Id;
            //    newrow.Service = $"{ExStr(item.FrameName, 15)} {ExStr(item.FrameSize, 15)} {ExStr(item.Unit, 10)}";
            //    newrow.UnitPrice = item.UnitPrice;
            //    newrow.DiscountedPrice = item.DiscountedPrice;
            //    newrow.Count = item.Count;
            //    newrow._Table = "Frame";
            //    ServiceTable.AddServiceRow(newrow);

            //}


            //foreach (AlpaDataSet.VCF_CostRow item in ucCost1.alpaDataSet.VCF_Cost)
            //{
            //    if (item.RowState == DataRowState.Deleted)
            //        continue;

            //    AlpaDataSet.ServiceRow newrow = ServiceTable.NewServiceRow();
            //    newrow.Id = item.Id;
            //    newrow.Service = item.Comment;
            //    newrow.UnitPrice = item.Price;
            //    newrow.DiscountedPrice = item.Price;
            //    newrow.Count = 1;
            //    newrow._Table = "Cost";
            //    ServiceTable.AddServiceRow(newrow);
            //}


            //grdvServices.UpdateSummary();
            //txbSumNetPrice.EditValue = Convert.ToInt32(colNetPrice.SummaryItem.SummaryValue);
            //grdvServices.FocusedRowHandle = focusedHande;
        }



        private string ExStr(string str, int length)
        {
            StringBuilder sb = new StringBuilder(str, length);
            for (int i = sb.Length; i < sb.Capacity; i++)
            {
                sb.Append(' ');
            }

            return sb.ToString();
        }





        private void imageListBoxControl1_SelectedIndexChanged(object sender, EventArgs e)
        {
            //navigationFrame1.SelectedPageIndex = lsbNavigationFrame.SelectedIndex;
        }





        //************************************************************************************************************************************


        private void bbiSave_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //UpdateRelaytedTable(_VCF_Id);
            ////DialogResult = DialogResult.OK;
        }

        private void bbiSaveClose_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //UpdateRelaytedTable(_VCF_Id);
            //DialogResult = DialogResult.OK;
            //this.Close();
        }

        private void ribbonControl1_Click(object sender, EventArgs e)
        {

        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void bbiPrint_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //ReportHelper.PrintCurrent(_VCF_Id);
        }

        private void bbiPrintPhoto_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //ReportHelper.PrintCurrentPhoto(_VCF_Id);
        }

        private void bbiExportPDF_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //ReportHelper.ExportPDFCurrent(_VCF_Id);
        }

        private void bbiRefresh_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //UserLookAndFeel defaultLF = UserLookAndFeel.Default;
            //defaultLF.SkinName = "WXI MahakSkinPatch";
        }

        private void bbiPhoto_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //XfrmPhoto xfrmPhoto = new XfrmPhoto(_VCF_Id);
            //xfrmPhoto.ShowDialog();
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValueNeeded(object sender, DevExpress.Data.UnboundSourceValueNeededEventArgs e)
        {
            // Handle this event to obtain data from your data source
            // e.Value = something /* TODO: Assign the real data here.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValuePushed(object sender, DevExpress.Data.UnboundSourceValuePushedEventArgs e)
        {
            // Handle this event to save modified data back to your data source
            // something = e.Value; /* TODO: Propagate the value into the storage.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource2_ValueNeeded(object sender, DevExpress.Data.UnboundSourceValueNeededEventArgs e)
        {
            // Handle this event to obtain data from your data source
            // e.Value = something /* TODO: Assign the real data here.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource2_ValuePushed(object sender, DevExpress.Data.UnboundSourceValuePushedEventArgs e)
        {
            // Handle this event to save modified data back to your data source
            // something = e.Value; /* TODO: Propagate the value into the storage.*/
        }





















        //************************************************************************************************************************************




    }
}
