
using DevExpress.Utils;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml.Linq;
using CncApp_Final.Data;
using CncApp_Final.Entities;
using CncApp_Final.Helper; // فرض می‌کنیم این فضای نام برای کلاس‌های کمکی است.
using CncApp_Final.Frm;


namespace CncApp_Final.Frm
{
    public partial class FrmOrder : DevExpress.XtraBars.Ribbon.RibbonForm
    {

        // خصوصیات برای نگهداری شناسه و وضعیت سفارش
        public int _Order_Id { get; private set; } = 0; // 0 for new order
        private readonly int _Order_Id_Org = -1;
        private bool _IsNewOrder = false;
        private readonly bool _IsOrderReadonly = false;

        // کانکست پایگاه داده
        private AppDbContext _dbContext;
        private Order _currentOrder;


        // سازنده برای سفارش جدید (بدون پارامتر)
        public FrmOrder()
        {
            InitializeComponent();
            _IsNewOrder = true;
            _Order_Id = 0; // ID صفر به معنی جدید است
            _dbContext = new AppDbContext(); // ایجاد یک کانکست جدید
        }

        // سازنده برای ویرایش سفارش موجود (با پارامتر)
        public FrmOrder(int order_Id, bool isOrderReadonly)
        {
            InitializeComponent();
            _Order_Id = order_Id;
            _Order_Id_Org = order_Id;
            _IsOrderReadonly = isOrderReadonly;
            _IsNewOrder = false;
            _dbContext = new AppDbContext(); // ایجاد یک کانکست جدید
        }



        //************************************************************************************************************************************



        private void FrmFacture_Load(object sender, EventArgs e)
        {
            //// This line of code is generated by Data Source Configuration Wizard
            //// Instantiate a new DBContext
            //CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();

            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.Orders.Load();
            //dbContext.OrderDetails.Load();
            //dbContext.Customers.Load();

            //// This line of code is generated by Data Source Configuration Wizard
            //orderDetailsBindingSource.DataSource = dbContext.OrderDetails.Local.ToBindingList();
            //orderBindingSource.DataSource = dbContext.Orders.Local.ToBindingList();
            //customersBindingSource.DataSource = dbContext.Customers.Local.ToBindingList();


            //InitControl();
            //InitDataToControl();

            // بارگذاری تمام مشتریان برای LookUpEdit
            _dbContext.Customers.Load();
            customersBindingSource.DataSource = _dbContext.Customers.Local.ToBindingList();

            // بقیه داده‌ها بر اساس وضعیت جدید یا ویرایش بارگذاری می‌شوند
            InitDataToControl();

            // تنظیم حالت فقط خواندنی (اگر لازم باشد)
            if (_IsOrderReadonly)
            {
                SetReadOnlyMode();
            }
        }

        //************************************************************************************************************************************

        #region Load Data To Form Control

        private void InitDataToControl()
        {
            if (_IsNewOrder)
            {
                // ایجاد شیء جدید و اتصال آن به BindingSource
                _currentOrder = new Order()
                {
                    OrderDate = DateTime.Now,
                    FaOrderDate = CalendarHelper.ToPersianDate(DateTime.Now),
                    DeliveryDate = DateTime.Now.AddDays(7), // تاریخ تحویل پیش‌فرض
                    FaDeliveryDate = CalendarHelper.ToPersianDate(DateTime.Now.AddDays(7)),
                    TransportCost = 0,
                    MiscCost = 0,
                    Discount = 0,
                    OrderDetails = new List<OrderDetails>() // لیست خالی جزئیات
                };
                orderBindingSource.DataSource = _currentOrder;
                orderDetailsBindingSource.DataSource = _currentOrder.OrderDetails;

                ribbonControl1.ApplicationCaption = "ثبت فاکتور جدید";
                txbVCF_Id.EditValue = "(جدید)"; // نمایش وضعیت جدید بودن در Ribbon
            }
            else
            {
                // بارگذاری سفارش موجود به همراه جزئیات و مشتری مرتبط
                var orderWithDetails = _dbContext.Orders
                    .Include(o => o.OrderDetails)
                    .Include(o => o.Customer)
                    .FirstOrDefault(o => o.Id == _Order_Id);

                if (orderWithDetails == null)
                {
                    MessageBox.Show("سفارش یافت نشد و بسته خواهد شد.", "خطا", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    this.Close();
                    return;
                }

                _currentOrder = orderWithDetails;
                // اتصال به BindingSource
                orderBindingSource.DataSource = _currentOrder;
                orderDetailsBindingSource.DataSource = _currentOrder.OrderDetails;

                ribbonControl1.ApplicationCaption = "ویرایش فاکتور: " + _Order_Id;
                txbVCF_Id.EditValue = _Order_Id.ToString();
            }

            // متدهای کمکی برای تنظیمات اولیه
            InitControl();
            //CalculateTotalAmount(); // محاسبه اولیه قیمت‌ها
        }

        #endregion

        //************************************************************************************************************************************

        #region Saving Logic

        private bool SaveOrder(bool closeAfterSave)
        {
            try
            {
                // 1. قطع اتصال داده‌ها (End Edit)
                orderBindingSource.EndEdit();
                grdvOrderDetails.CloseEditor();
                grdvOrderDetails.UpdateCurrentRow();

                // به‌روزرسانی فیلدهای محاسبه شده (در صورت نیاز)
                //CalculateTotalAmount();

                // 2. به‌روزرسانی تاریخ‌ها از ورودی فارسی (اگر دستی تغییر کرده باشند)
                _currentOrder.OrderDate = CalendarHelper.ToGregorianDate(txbFaOrderDate.Text);
                _currentOrder.DeliveryDate = CalendarHelper.ToGregorianDate(txbFaDeliveryDate.Text);

                if (_IsNewOrder)
                {
                    // افزودن سفارش جدید به DbSet
                    _dbContext.Orders.Add(_currentOrder);
                    // چون OrderDetails قبلاً به Order متصل شده، نیازی به افزودن صریح نیست.
                }
                else
                {
                    // پیوست کردن آبجکت در حالت ویرایش
                    _dbContext.Orders.Attach(_currentOrder);
                    _dbContext.Entry(_currentOrder).State = EntityState.Modified;
                    // اگر تغییراتی در لیست OrderDetails داده شده باشد، باید وضعیت آیتم‌های آن نیز مدیریت شود
                    // اما به دلیل استفاده از Local.ToBindingList در Load، EF معمولاً تغییرات را رهگیری می‌کند.
                    // برای اطمینان بیشتر، می‌توانید قبل از ذخیره، تغییرات دستی را اعمال کنید.

                    // حذف جزئیاتی که از گرید حذف شده‌اند (اگر قبلا حذف دستی نشده باشد)
                    // این قسمت نیاز به پیاده‌سازی منطق حذف در رویدادهای گرید دارد،
                    // اما به طور ساده، در اینجا تغییرات کلی را ذخیره می‌کنیم.
                }

                // 3. ذخیره تغییرات در پایگاه داده
                _dbContext.SaveChanges();

                // در صورت ذخیره موفق، شناسه جدید را به‌روزرسانی می‌کنیم
                if (_IsNewOrder)
                {
                    _Order_Id = _currentOrder.Id;
                    _IsNewOrder = false; // حالا دیگر جدید نیست
                    ribbonControl1.ApplicationCaption = "ویرایش فاکتور: " + _Order_Id;
                    txbVCF_Id.EditValue = _Order_Id.ToString();
                }

                MessageBox.Show("سفارش با موفقیت ذخیره شد.", "ذخیره", MessageBoxButtons.OK, MessageBoxIcon.Information);

                if (closeAfterSave)
                {
                    DialogResult = DialogResult.OK;
                    this.Close();
                }
                return true;

            }
            catch (Exception ex)
            {
                MessageBox.Show("خطا در ذخیره سفارش: " + ex.Message, "خطا", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            }
        }

        #endregion
        //************************************************************************************************************************************



        //#region Load Data To Form Control


        //private void InitDataToControl()
        //{
        //    if (_IsNewFaktor)
        //    {
        //        int orderId = _Order_Id; // یا از فرم بگیرید
        //        CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();

        //        var orderWithDetails = dbContext.Orders
        //            .Include(o => o.OrderDetails)
        //            .Include(o => o.Customer)
        //            .FirstOrDefault(o => o.Id == orderId);

        //        if (orderWithDetails == null)
        //        {
        //            MessageBox.Show("سفارش یافت نشد.");
        //            orderBindingSource.DataSource = null;
        //            orderDetailsBindingSource.DataSource = null;
        //            return;
        //        }

        //        // فقط سفارش انتخاب شده
        //        orderBindingSource.DataSource = orderWithDetails;

        //        // فقط جزئیات همین سفارش (بهترین روش برای BindingSource)
        //        orderDetailsBindingSource.DataSource = orderWithDetails.OrderDetails;

        //        //_VCF_Id = (int)vCFXTableAdapter.GetNewVCF_Id();
        //        //InitNewRowVCF_X(_VCF_Id);
        //        ribbonControl1.ApplicationCaption = "ثبت فاکتور جدید";
        //    }
        //    else
        //    {
        //        int orderId = _Order_Id; // یا از فرم بگیرید
        //        CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();

        //        var orderWithDetails = dbContext.Orders
        //            .Include(o => o.OrderDetails)
        //            .Include(o => o.Customer)
        //            .FirstOrDefault(o => o.Id == orderId);

        //        if (orderWithDetails == null)
        //        {
        //            MessageBox.Show("سفارش یافت نشد.");
        //            orderBindingSource.DataSource = null;
        //            orderDetailsBindingSource.DataSource = null;
        //            return;
        //        }

        //        // فقط سفارش انتخاب شده
        //        orderBindingSource.DataSource = orderWithDetails;

        //        // فقط جزئیات همین سفارش (بهترین روش برای BindingSource)
        //        orderDetailsBindingSource.DataSource = orderWithDetails.OrderDetails;

        //        //_VCF_Id = (int)vCFXTableAdapter.GetNewVCF_Id();
        //        //InitNewRowVCF_X(_VCF_Id);
        //        ribbonControl1.ApplicationCaption = "ویرایش فاکتور";

        //    }



        ////serviceTableAdapter.Fill(this.alpaDataSet.Service, _VCF_Id);

        ////ucFrameSelector1.ServiceTable = alpaDataSet.Service;
        //ucFrameSelector1.VCF_Id(_VCF_Id);
        //ucAddress1.VCF_Id(_VCF_Id);
        //ucCost1.VCF_Id(_VCF_Id);
        //ucVCF_Space1.VCF_Id(_VCF_Id);

        //Service_RowsChanged(this, EventArgs.Empty);

        //if (_IsNewFaktor)
        //{
        //    lueCustomer.EditValue = "2";
        //    lueCustomer.Focus();
        //}

        //lsbNavigationFrame.SelectedIndex = 0;

        //}


        //************************************************************************************************************************************

        #region Events (Completed)

        private void bbiSave_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SaveOrder(false); // ذخیره بدون بستن
        }

        private void bbiSaveClose_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SaveOrder(true); // ذخیره و بستن
        }

        private void bbiRefresh_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            // متد بازسازی UI و بارگذاری مجدد (Load مجدد)
            // در محیط واقعی، ابتدا باید تغییرات ذخیره نشده را مدیریت کرد.
            if (_Order_Id > 0 && !_IsNewOrder)
            {
                // بارگذاری مجدد سفارش موجود
                _dbContext = new AppDbContext();
                InitDataToControl();
                MessageBox.Show("داده‌ها مجدداً بارگذاری شدند.", "بارگذاری مجدد", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else
            {
                MessageBox.Show("امکان بارگذاری مجدد برای سفارش جدید یا ذخیره‌نشده وجود ندارد.", "اطلاع", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        private void btnNewCustomer_Click(object sender, EventArgs e)
        {
            FrmCustomerEdit newFrmCustomers = new FrmCustomerEdit(0, false);
            newFrmCustomers.ShowDialog();

            if (newFrmCustomers.DialogResult == DialogResult.OK)
            {
                // فرض می‌کنیم FrmCustomers لیست مشتریان را به‌روز کرده و باید دوباره لود شود
                _dbContext.Customers.Load();
                customersBindingSource.DataSource = _dbContext.Customers.Local.ToBindingList();
                lueCustomer.Refresh();
                lueCustomer.EditValue = newFrmCustomers._New_Customer_Id;
                // اگر مشتری جدیدی ثبت شده باشد، می‌توانید EditValue را به آن مشتری جدید تنظیم کنید.
            }
        }

        //// این رویدادها را برای فراخوانی CalculateTotalAmount اضافه کنید:
        //private void txbTransportCost_EditValueChanged(object sender, EventArgs e) => CalculateTotalAmount();
        //private void txbMiscCost_EditValueChanged(object sender, EventArgs e) => CalculateTotalAmount();
        //private void textEdit7_EditValueChanged(object sender, EventArgs e) => CalculateTotalAmount(); // تخفیف

        // همچنین باید رویدادهای مربوط به تغییر در گرید (grdvOrderDetails) را نیز مدیریت کنید.
        // مثلاً: grdvOrderDetails_CellValueChanged

        #endregion


        //************************************************************************************************************************************

        #region Helper & UI Methods

        private void SetReadOnlyMode()
        {
            // غیرفعال کردن تمام کنترل‌های ورودی
            groupControl4.Enabled = false;
            groupControl1.Enabled = false;
            gridControl.Enabled = false;
            bbiSave.Enabled = false;
            bbiSaveClose.Enabled = false;
            btnNewCustomer.Enabled = false;
            // ... سایر دکمه‌های ویرایش
        }
        private void InitNewRowVCF_X(int _VCF_Id)
        {
            //AlpaDataSet.VCFXRow newRow = this.alpaDataSet.VCFX.NewVCFXRow();
            //newRow.VCF_Time = DateTime.Now.ToString("HH:mm");
            //newRow.VCF_Id = _VCF_Id;

            ////txbVCF_Id.EditValue = newRow.VCF_Id;
            ////txbVCF_Id.EditValue = 77;

            //newRow.VCF_NaghdB = 0;
            //newRow.VCF_KartKhanB = 0;
            //newRow.VCF_KartKhan = 0;
            //newRow.VCF_Vasetehtype = false;
            //newRow.VCF_VasetehPrice = 0;
            //newRow.VCF_CountFirst = 0;
            //newRow.VCF_Cust_Rent = 0;
            //newRow.VC_Hazineh = 0;
            //newRow.VCT_Price = 0;
            //newRow.VCT_Day = 0;
            //newRow.VCTName = "";
            //newRow.VCT_LateDayPrice = 0;




            //this.alpaDataSet.VCFX.AddVCFXRow(newRow);
        }

        #endregion


        //************************************************************************************************************************************





        #region ***************  Init control focused color    ***************

        private void InitControl()
        {
            //txbTime.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            //txbDate.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            //txbRDate.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            //txbDays.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            ////txbPriceIndex.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;

            //txbComment.Properties.AppearanceFocused.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
            ////gridView1.Appearance.FocusedCell.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;
        }

        private int _color;
        private void gridControl1_Enter(object sender, EventArgs e)
        {
            //_color = gridView1.Appearance.FocusedCell.BackColor.ToArgb();
            //gridView1.Appearance.FocusedCell.BackColor = lueCustomer.Properties.AppearanceFocused.BackColor;

            //var culture = System.Globalization.CultureInfo.GetCultureInfo("fa-IR");
            //var language = InputLanguage.FromCulture(culture);
            //if (InputLanguage.InstalledInputLanguages.IndexOf(language) >= 0)
            //    InputLanguage.CurrentInputLanguage = language;
        }

        private void gridControl1_Leave(object sender, EventArgs e)
        {
            //gridView1.PostEditor();

            //gridView1.Appearance.FocusedCell.BackColor = Color.FromArgb(_color);
        }


        InputLanguage original;
        private void textBox_Enter(object sender, EventArgs e)
        {
            original = InputLanguage.CurrentInputLanguage;
            var culture = System.Globalization.CultureInfo.GetCultureInfo("fa-IR");
            var language = InputLanguage.FromCulture(culture);
            if (InputLanguage.InstalledInputLanguages.IndexOf(language) >= 0)
                InputLanguage.CurrentInputLanguage = language;
            else
                InputLanguage.CurrentInputLanguage = InputLanguage.DefaultInputLanguage;
        }

        private void textBox_Leave(object sender, EventArgs e)
        {
            InputLanguage.CurrentInputLanguage = original;
        }

        #endregion


        //************************************************************************************************************************************




        //************************************************************************************************************************************




        //************************************************************************************************************************************


        #region Temp And Unused Method



        /// <summary>
                /// کرفتن متن ستون از گریدیو
                /// </summary>
                /// <param name="gw"></param>
                /// <param name="column"></param>
                /// <returns></returns>
        private static string GetTextColumnValue(GridView gw, string column)
        {
            if (gw.RowCount <= 0)
            {
                return " ";
            }
            try
            {
                int i = gw.FocusedRowHandle;
                return gw.IsGroupRow(i)
                ? gw.GetGroupRowValue(i, gw.Columns[column]).ToString()
                : gw.GetRowCellValue(i, column).ToString();
            }
            catch
            {
                MessageBox.Show($@"درخواستی در کنترل انتخابی موجود نمی باشد( {column} ) ستون");
                return " ";
            }
        }

        #endregion


        //************************************************************************************************************************************


        //private void btnNewCustomer_Click(object sender, EventArgs e)
        //{
        //    FrmCustomers frmCustomers = new FrmCustomers();
        //    frmCustomers.ShowDialog();

        //    //if (frmNewCustomer.C_Code != null)
        //    //{
        //    //    this.cUSTOMERTableAdapter.Fill(this.alpaDataSet.CUSTOMER);
        //    //    lueCustomer.EditValue = frmNewCustomer.C_Code;
        //    //}
        //}




        //************************************************************************************************************************************
        //************************************************************************************************************************************


        //private void bbiSave_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        //{
        //    //UpdateRelaytedTable(_VCF_Id);
        //    DialogResult = DialogResult.OK;
        //}

        //private void bbiSaveClose_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        //{
        //    //UpdateRelaytedTable(_VCF_Id);
        //    DialogResult = DialogResult.OK;
        //    this.Close();
        //}

        private void ribbonControl1_Click(object sender, EventArgs e)
        {

        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void bbiPrint_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //ReportHelper.PrintCurrent(_VCF_Id);
        }

        private void bbiPrintPhoto_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //ReportHelper.PrintCurrentPhoto(_VCF_Id);
        }

        private void bbiExportPDF_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //ReportHelper.ExportPDFCurrent(_VCF_Id);
        }

        //private void bbiRefresh_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        //{
        //    //UserLookAndFeel defaultLF = UserLookAndFeel.Default;
        //    //defaultLF.SkinName = "WXI MahakSkinPatch";
        //}

        private void bbiPhoto_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //XfrmPhoto xfrmPhoto = new XfrmPhoto(_VCF_Id);
            //xfrmPhoto.ShowDialog();
        }



        //*************************************************************************************************************************************
        //*************************************************************************************************************************************
        //*************************************************************************************************************************************
        //*************************************************************************************************************************************
        //*************************************************************************************************************************************
        
        
        // در کلاس FrmOrder
        // متد فراخوانی فرم ویرایش جزئیات

        private void OpenOrderDetailForEdit(OrderDetails detailToEdit)
        {
            FrmOrderDetails frmOrderDetailEdit = new FrmOrderDetails(detailToEdit, _dbContext);
            DialogResult result = frmOrderDetailEdit.ShowDialog();
            if (result == DialogResult.OK)
            {
                grdvOrderDetails.RefreshData();

                // محاسبه مجدد مجموع هزینه‌ها
                //CalculateTotalAmount();
            }
            else
            {
                // اگر کاربر Cancel کرد، باید تغییرات در شیء detailToEdit را Revert کنیم.
                // این بخش پیچیده‌تر است و معمولاً نیاز به Clone کردن شیء قبل از ارسال دارد.
                // در حالت ساده، فرض می‌کنیم کاربر اگر تغییرات را نخواهد، کل فرم Order را ذخیره نمی‌کند.

                // اگر می‌خواهید حالت Cancel نیز کار کند، باید ابتدا از شیء یک کپی (Deep Clone) بگیرید و آن را به فرم ویرایش ارسال کنید، 
                // و اگر OK شد، کپی را جایگزین شیء اصلی در Context کنید.
            }
        }

        // رویداد DoubleClick در گرید OrderDetails (اصلاح شده)
        private void gridControl_DoubleClick(object sender, EventArgs e)
        {
            GridView view = gridControl.MainView as GridView;
            GridHitInfo info = view.CalcHitInfo((e as DXMouseEventArgs).Location);

            if ((info.InRow || info.InRowCell) && view.IsDataRow(info.RowHandle))
            {
                // دریافت شیء کامل OrderDetails از سطر فوکوس شده
                OrderDetails detailToEdit = view.GetRow(info.RowHandle) as OrderDetails;

                if (detailToEdit != null)
                {
                    // EndEdit برای اطمینان از اعمال هرگونه تغییرات ناتمام در سطر
                    view.CloseEditor();
                    view.UpdateCurrentRow();

                    OpenOrderDetailForEdit(detailToEdit);
                }
            }
        }

        //// حفظ منطق ذخیره‌سازی اصلی:
        //private bool SaveOrder(bool closeAfterSave)
        //{
        //    // ... (EndEdit, UpdateCurrentRow, CalculateTotalAmount)

        //    // در این مرحله، Context (DbContext_) ما تمام تغییرات (Modified/Added/Deleted) را ردیابی می‌کند.

        //    // **فقط در صورتی که سفارش ویرایش شده باشد و تغییراتی در آن باشد:**
        //    // if (_dbContext.ChangeTracker.HasChanges()) 
        //    // {
        //    _dbContext.SaveChanges(); // این خط تمام تغییرات ردیابی شده را به دیتابیس می‌فرستد.
        //                              // ... (مدیریت ID جدید و پیام‌های موفقیت)
        //                              // }

        //    // ...
        //}




















    }
}
