using DevExpress.XtraEditors;
using DevExpress.XtraLayout;
using DevExpress.XtraLayout.Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using CncApp_Final.Frm;
using CncApp_Final.TempFrm;

namespace CncApp_Final.Frm
{
    public partial class FrmReceipts : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public FrmReceipts()
        {
            InitializeComponent();
            
        }

        private void FrmReceipts_Load(object sender, EventArgs e)
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Receipts.Load();
            // This line of code is generated by Data Source Configuration Wizard
            receiptsBindingSource.DataSource = dbContext.Receipts.Local.ToBindingList();
        }

        private void bbiNewReceipt_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FrmReceiptEdit frmCustomerEdit = new FrmReceiptEdit(0, false);
            frmCustomerEdit.ShowDialog();
        }

        private void bbiEditReceipt_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            int receipt_Id = (int)gridView.GetFocusedRowCellValue(colId);
            FrmReceiptEdit frmCustomerEdit = new FrmReceiptEdit(receipt_Id, false);
            frmCustomerEdit.ShowDialog();
        }


        
    }
}
