using CncApp_Final.Entities;
using CncApp_Final.Helper;
using DevExpress.Data.Controls.ExpressionEditor;
using DevExpress.Data.Controls.ExpressionEditor;
using DevExpress.Data.Filtering;
using DevExpress.Data.Filtering.Helpers;
using DevExpress.DataAccess.ExpressionEditor;
using DevExpress.DataAccess.Native.ExpressionEditor;
//using DevExpress.XtraRichEdit
using DevExpress.Xpf.ExpressionEditor;
using DevExpress.Xpf.ExpressionEditor.Native;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraRichEdit.API.Native;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Text;
using System.Windows.Forms;



namespace CncApp_Final.Frm
{
    public partial class FrmSheetFormulaEditor : DevExpress.XtraEditors.XtraForm
    {
        public FrmSheetFormulaEditor()
        {
            InitializeComponent();
            

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Sheets.Load();
            // This line of code is generated by Data Source Configuration Wizard
            sheetsBindingSource.DataSource = dbContext.Sheets.Local.ToBindingList();

            //foreach (GridColumn col in gridView1.Columns)
            //{
            //    if (string.IsNullOrEmpty(col.Caption) || col.Caption != col.FieldName)
            //    {
            //        col.Caption = col.FieldName;  // Caption رو دقیقاً برابر FieldName کن
            //    }
            //}


            //gridControl1.DataSource = GetData();
            AddUnboundColumns();
            PopulateComboWithUnboundColumns();
            comboBoxEdit1.EditValue = "Expression A";
        }

        private void FrmSheetFormulaEditor_Load(object sender, EventArgs e)
        {
            
        }

      

        private void comboBoxEdit1_SelectedIndexChanged(object sender, EventArgs e)
        {
            GridColumn unboundColumn = gridView1.Columns[comboBoxEdit1.EditValue.ToString()];
            unboundExpressionPanel1.StartEdit(unboundColumn);
        }


        void AddUnboundColumns()
        {
            GridColumn col1 = gridView1.Columns.AddVisible("Expression A");
            col1.UnboundType = DevExpress.Data.UnboundColumnType.Decimal;
            col1.UnboundExpression = "[UnitPrice] * [UnitsInStock]";

            GridColumn col2 = gridView1.Columns.AddVisible("Expression B");
            col2.UnboundType = DevExpress.Data.UnboundColumnType.Object;
        }
        void PopulateComboWithUnboundColumns()
        {
            foreach (GridColumn col in gridView1.Columns)
            {
                if (col.UnboundType != DevExpress.Data.UnboundColumnType.Bound)
                    comboBoxEdit1.Properties.Items.Add(col.FieldName);
            }
        }
        DataTable GetData()
        {
            //if (File.Exists("northwind_data.xml"))
            //{
            //    DataSet ds = new DataSet();
            //    ds.ReadXml("northwind_data.xml", XmlReadMode.ReadSchema);
            //    return ds.Tables[0];
            //}
            //else
            //{
            //    DataTable dt = new DataTable();
            //    dt.Columns.Add("ID", typeof(int));
            //    dt.Columns.Add("Info", typeof(string));
            //    dt.Columns.Add("UnitPrice", typeof(decimal));
            //    dt.Columns.Add("UnitsInStock", typeof(int));
            //    for (int i = 0; i < 6; i++)
            //    {
            //        dt.Rows.Add(i, "Info" + i, 3.37 * (i + 1), i + 3);
            //    }

            //    DataTable dt = new DataTable();
            //    return dt;
            //}

            DataTable dt = new DataTable();
            return dt;
        }

        private void unboundExpressionPanel1_Resize(object sender, EventArgs e)
        {
            this.Text = this.Size.ToString();
        }

        private void vGridControl1_Click(object sender, EventArgs e)
        {

        }

        private void vGridControl1_CustomUnboundData(object sender, DevExpress.XtraVerticalGrid.Events.CustomDataEventArgs e)
        {
            
        }

        private void gridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            if (e.IsGetData)
            {
                Sheet currentSheet = e.Row as Sheet;
                if (currentSheet == null) return;

                // اول مطمئن شو که قیمت‌ها بر اساس فرمول اختصاصی این ردیف محاسبه شدن
                SheetCalculator.Calculate(currentSheet);  // همون کلاس محاسبه‌گر قبلی

                // حالا مقدار محاسبه‌شده رو برای ستون مربوطه برگردون
                if (e.Column.FieldName == "SheetPrice")
                    e.Value = currentSheet.SheetPrice;

                else if (e.Column.FieldName == "PicesPrice")
                    e.Value = currentSheet.PicesPrice;

                // می‌تونی ستون‌های unbound دیگه هم اضافه کنی
            }
        }
    }
}
