using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace CncApp_Final.Frm
{
    public partial class FrmWareHouse : DevExpress.XtraEditors.XtraForm
    {
        public FrmWareHouse()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Warehouses.Load();
            // This line of code is generated by Data Source Configuration Wizard
            warehousesBindingSource.DataSource = dbContext.Warehouses.Local.ToBindingList();
        }
    }
}