using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors.Controls;
using System.Data.Entity;

namespace CncApp_Final
{
    public partial class RibbonForm2 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public RibbonForm2()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Orders.Load();
            var x = dbContext.Orders.ToList();
            //gridControl1.DataSource = x;
            // This line of code is generated by Data Source Configuration Wizard
            ordersBindingSource.DataSource = dbContext.Orders.Local.ToBindingList();
        }

        private void dateEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void RibbonForm2_Load(object sender, EventArgs e)
        {

        }
    }
}