using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using CncApp_Final.Entities;

namespace CncApp_Final.TempFrm
{
    public partial class XtraForm1 : DevExpress.XtraEditors.XtraForm
    {
        public XtraForm1()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CncApp_Final.Data.AppDbContext dbContext = new CncApp_Final.Data.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Orders.Load();
            var x = ((Order)dbContext.Orders.ToList()[0]).FaDeliveryDate;
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = dbContext.Orders.Local.ToBindingList();
        }
    }
}